SEC = {
    'NO_FLAGS' :    '0x000',
    'ALLOC' :       '0x001',
    'LOAD' :        '0x002',
    'RELOC' :       '0x004',
    'READONLY' :    '0x008',
    'CODE' :        '0x010',
    'DATA' :        '0x020',
    'ROM' :         '0x040',
    'CONSTRUCTOR' : '0x080',
    'HAS_CONTENTS': '0x100',
    'NEVER_LOAD':   '0x200',
    'THREAD_LOCAL': '0x400',
    'HAS_GOT_REF':  '0x800',
    'IS_COMMON':    '0x1000',
    'DEBUGGING':    '0x2000',
    'IN_MEMORY':    '0x4000',
    'EXCLUDE':      '0x8000',
    'SORT_ENTRIES': '0x10000',
    'LINK_ONCE':    '0x20000',
    'LINK_DUPLICATES':          '0xc0000',
    'LINK_DUPLICATES_DISCARD':  '0x0',
    'LINK_DUPLICATES_ONE_ONLY': '0x40000',
    'LINK_DUPLICATES_SAME_SIZE':'0x80000',
    #'LINK_DUPLICATES_SAME_CONTENTS':    '\',
    'LINKER_CREATED':           '0x100000',
    'KEEP':         '0x200000',
    'SMALL_DATA':   '0x400000',
    'MERGE':        '0x800000',
    'STRINGS':      '0x1000000',
    'GROUP':        '0x2000000',
    'COFF_SHARED_LIBRARY':  '0x4000000',
    'ELF_REVERSE_COPY':     '0x4000000',
    'COFF_SHARED':  '0x8000000',
    'TIC54X_BLOCK': '0x10000000',
    'TIC54X_CLINK': '0x20000000',
    'COFF_NOREAD':  '0x40000000',
}

relationList = (
    ('.text',   SEC['HAS_CONTENTS'] | SEC['ALLOC'] | SEC['LOAD'] | SEC['READONLY'] | SEC['CODE']),
    ('.rodata', SEC['HAS_CONTENTS'] | SEC['ALLOC'] | SEC['LOAD'] | SEC['READONLY'] | SEC['DATA']),
    ('.data',   SEC['HAS_CONTENTS'] | SEC['ALLOC'] | SEC['LOAD'] | SEC['DATA']),
    ('.bss',    SEC['ALLOC']),
    ('.interp', SEC['HAS_CONTENTS'] | SEC['ALLOC'] | SEC['LOAD'] | SEC['READONLY'] | SEC['DATA']),
    ('.sdata',  SEC['HAS_CONTENTS'] | SEC['ALLOC'] | SEC['LOAD'] | SEC['DATA'] | SEC['SMALL_DATA']),
    ('.comment',SEC['HAS_CONTENTS']),

    ('.note',               SEC['ALLOC'] | SEC['READONLY']),
    ('.note.gnu.build-id',  SEC['ALLOC'] | SEC['READONLY']),
    ('.hash',       SEC['ALLOC'] | SEC['READONLY']),
    ('.gnu.hash',   SEC['ALLOC'] | SEC['READONLY']),
    ('.dynsym',     SEC['ALLOC'] | SEC['READONLY']),
    ('.dynstr',     SEC['ALLOC'] | SEC['READONLY']),
    ('.version',    SEC['ALLOC'] | SEC['READONLY']),
    ('.version_r',  SEC['ALLOC'] | SEC['READONLY']),
    ('.rela.plt',   SEC['ALLOC'] | SEC['READONLY']),
    ('.dynamic',    SEC['ALLOC'] | SEC['LOAD'] | SEC['HAS_CONTENTS'] | SEC['IN_MEMORY'] | SEC['LINKER_CREATED']),
    ('.got.plt',    SEC['ALLOC'] | SEC['LOAD'] | SEC['HAS_CONTENTS'] | SEC['IN_MEMORY'] | SEC['LINKER_CREATED']),
)
